version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  # Serviço centralizado para manter informações  de configurações e nomenclaturas
  # Usado pelo kafka para sincronizar configurações entre diferentes clusters
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper